version: '2'
services:
  postgres:
    image: "postgres:13-alpine"
    restart: "always"
    volumes:
      -  "testdb-data:/var/lib/postgresql/data"
    ports:
      -  "54321:5432"
    environment:
      POSTGRES_USER: "testuser"
      POSTGRES_PASSWORD: "qwer1234"
      POSTGRES_DB: "testdb"
    mem_limit: "8g"

volumes:
  testdb-data:
